import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header class="bg-white divide-y border-b fixed inset-x-0 z-10">
        <div class="flex justify-between items-center h-14 mx-4">
          <div class="-ml-3">
          <img
            className="h-8 w-8 ml-3"
            src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg"
            alt="Workflow"
          />
          </div>
          <div class="flex items-center justify-center flex-grow">
          <input type="text" placeholder="Search" class="border border-gray-400 h-10  px-1 py-2 focus:outline-none focus:border-blue-600 w-3/5 max-w-lg"/>
          <button class="bg-gray-200 flex items-center justify-center h-10 w-16 border border-gray-400 border-l-0 hover:bg-gray-300">
            <i class="material-icons">search</i>
          </button>
          </div>
          <div class="flex items-center justify-center space-x-4">
                <button class="flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                  <path d="M12 14l9-5-9-5-9 5 9 5z" />
                  <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
                </svg>
                </button>
                <button class="flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                    <path d="M12 14l9-5-9-5-9 5 9 5z" />
                    <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
                  </svg>
                </button>
                <button class="flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                    <path d="M12 14l9-5-9-5-9 5 9 5z" />
                    <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
                  </svg>
                </button>
                <button>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                      <path d="M12 14l9-5-9-5-9 5 9 5z" />
                      <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                      <path stroke-linecap="round" stroke-linejoin="round" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
                    </svg>
                </button>
          </div>
        </div>
        <div class="flex items-center px-2 py-2 px-4 space-x-3 select-none overflow-x-scroll hidden-scrollbar hidden-scrollbar::-webkit-scrollbar">
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">All Recommendations</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Tailwindcss</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Wrestling</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Javascript</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Python</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Coding</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">News</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">CSS</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Computer Science</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Comedy</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Tailwindcss</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Javascript</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Wrestling</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Python</span>
            <span class="px-2 py-1 text-gray-800 h-8 whitespace-nowrap">Coding</span>
        </div>
      </header>

      <div class="px-3 pt-24 grid grid-cols-12 gap-5 bg-gray-100 h-full w-full fixed">
        <div class="pt-6 bg-white col-span-2 h-full overflow-y-scroll hidden-scrollbar hidden-scrollbar::-webkit-scrollbar">
            22222
            <div class="h-24 bg-gray-300 my-5"></div>
            <div class="h-24 bg-gray-300 my-5"></div>
            <div class="h-24 bg-gray-300 my-5"></div>
            <div class="h-24 bg-gray-300 my-5"></div>
            <div class="h-24 bg-gray-300 my-5"></div>
            <div class="h-24 bg-gray-300 my-5"></div>
        </div>   
        <div class="pt-6 bg-white col-span-7 h-full overflow-y-scroll hidden-scrollbar hidden-scrollbar::-webkit-scrollbar">
            77777
            <div class="h-64 bg-gray-300 my-5">
              <div class="flex items-center justify-between">
                <div class="flex items-center">
                  <div class="mx-2 my-2 w-9 h-9 bg-gray-500 rounded-full"></div>
                  <div class="mx-2 my-2">username</div>
                </div>
                <div class="mx-4 my-2">2020-5-1</div>
              </div>
              <div class="">main</div>
              <div class="float-right mr-5">
                <div class="">booktitle</div>
                <div class="">author</div>
              </div>
              <div class="mt-16">sub</div>
            </div>
            <div class="h-64 bg-gray-300 my-5"></div>
            <div class="h-64 bg-gray-300 my-5"></div>
            <div class="h-64 bg-gray-300 my-5"></div>
            <div class="h-64 bg-gray-300 my-5"></div>
            <div class="h-64 bg-gray-300 my-5"></div>
        </div>
        <div class="pt-6 bg-white col-span-3 h-full overflow-y-scroll hidden-scrollbar hidden-scrollbar::-webkit-scrollbar">
            333333
            <div class="h-48 bg-gray-300 my-5"></div>
            <div class="h-24 bg-gray-300 my-5"></div>
            <div class="h-48 bg-gray-300 my-5"></div>
            <div class="h-24 bg-gray-300 my-5"></div>
            <div class="h-24 bg-gray-300 my-5"></div>
            <div class="h-48 bg-gray-300 my-5"></div>
        </div>
      </div>
    </div>
  )
}
